### ISSUE TITLE
more info about red.redPath setting

### ISSUE THREAD

**Issue by ifmihai** [red/VScode-extension#20]
Took me a while to figure out what i have to write exactly in redPath setting.
I'm on windows 10.
I'm a below average user of Visual Studio Code, and newbie in Red.

When i read this bit:

> Specify the full path of the red toolchain
> "red.redPath": "/home/user1/tools/red-latest"

I thought, ok, linux, but I'm on windows, and what's a toolchain? 😄 

I figure out through trial and error, that i had to write:
`c:\\work\\red\\red.exe`
(because that's where i put red.exe on my hdd)

I think it would help new people, if this bit was added to readme.

**Comment by bitbegin** [comment]
For windows user: `c:\\work\\red\\red.exe` or `c:\work\red\red.exe` or `c:/work/red/red.exe` are all ok.

Recommend you to use  `c:/work/red/red.exe`
