### ISSUE TITLE
When the redPath contains a space hitting f6 or f7 will not work.

### ISSUE THREAD

**Issue by smarks159** [red/VScode-extension#21]
I am using windows7 and I am using version 0.2.2 of the extension

If the redPath contains a space in it then hitting f6 or f7 will not work. The problem is that the command that gets generated in the integrated console does not place quotes around the path to the red executable. It does, however, place quotes around the path to the target file.

**Comment by hyzwhu** [comment]
I have tried to set the path with the space escape  , it did not work. And tried to use the environment path of the system, it did not work also. 
This is the vscode problems. so it is better to use the path without space character.
@qtxie
