### ISSUE TITLE
Red command shortcuts not working on latest VSCode

### ISSUE THREAD

**Issue by dander** [red/VScode-extension#27]
Reported by @9214: https://gitter.im/red/chit-chat?at=5b2d2f0a59799e701738dcde

The following error message is displayed:
![image](https://user-images.githubusercontent.com/1302979/41807657-ccf1493e-7686-11e8-9f96-fc326d2372bb.png)

It appears related to some behavioral change to VSCode, which may be fixed in a future release. See https://github.com/liximomo/vscode-sftp/pull/209

**Comment by 9214** [comment]
Works as usual in Insiders edition, which suggest that MS either patched the change or rolled it back. As @dander pointed out, the fix itself is trivial. 

Only F6 and F7 hotkeys do not work, right-click contextual menu is OK.
