### ISSUE TITLE
Autocomplete wrong function definitions / autocomplete stop working

### ISSUE THREAD

**Issue by Re-git** [red/VScode-extension#30]
I have recorded the problems I have with VScode extension for Red on my PC.
1. When using autocomplete the definitions of functions that are highlighted are wrong.
2. If after starting to type a word (and autocompletion widget shows) i erase the character. Then autocomplete(intelisense) stops working and never shows again until I restart VScode.

![alt](https://i.imgur.com/tqwyeCn.gif)

**Comment by qtxie** [comment]
I cannot reproduce it. I works fine with vscode 1.29.1 and Red 0.6.4.

**Comment by bitbegin** [comment]
should be worked for 0.3.0
