### ISSUE TITLE
F6 key gives an error

### ISSUE THREAD

**Issue by ghost** [red/VScode-extension#32]
In version 0.3.2. hitting the F6 key gives:
    error: command 'reds.interpret' not found

When I change "keybindings" in package.json such that red.interpret / red.compile are come after  reds.interpret / reds.compile the error goes away.

But I guess that is not the solution ...

**Comment by MartenH** [comment]
In version 0.3.2 I have this issue also. package.json in my case contains duplicate shortcuts for F6 and F7. Removing the duplicates will fix the issue: From original package.json
	{
				"command": "red.interpret",
				"key": "F6"
			},
			{
				"command": "red.compile",
				"key": "F7"
			},
			{
				"command": "reds.interpret",
				"key": "F6"
			},
			{
				"command": "reds.compile",
				"key": "F7"
			},

**Comment by bitbegin** [comment]
Should delete "reds.interpret", as Red/System can't be interpreted, but you can still use F7 to compile a Red/System file.
