### ISSUE TITLE
 Can't work with this 'Red' version

### ISSUE THREAD

**Issue by jefurry** [red/VScode-extension#33]
[Error - 6:40:47 AM] Server initialization failed.
  Message: Can't work with this 'Red' version
Please make sure that your Red toolchain newer than red-09jan19-acf34929.exe!
  Code: -32002

Mac 10.14.4 
VSCode 1.33.1 (1.33.1)
red 0.6.4

**Comment by bitbegin** [comment]
@jefurry  please update red toolchain with `red.exe` daily version, and excute `red.exe --cli`

**Comment by jefurry** [comment]
@bitbegin Thanks, got it!
