### ISSUE TITLE
Space on paths configuration

### ISSUE THREAD

**Issue by GiuseppeChillemi** [red/VScode-extension#35]
On Windows 10 I was not able to configure a path with a space under the extension config. 

All my attempts and support are here: [Gitter](https://gitter.im/red/bugs?at=5d129aecec8b5d01bd85bbc3)

**Comment by dirtbagger** [comment]
I think I'm having the same or a related problem.  Because of the space in the path to my Red folder, the path isn't handled properly.  I don't know if this is a Red issue or an issue with VSC and the plugin.

**Comment by vazub** [comment]
@GiuseppeChillemi spaces seem to be handled properly with the latest extension update 0.3.6, apparently fixed with this commit https://github.com/red/VScode-extension/commit/808aaf67d0aa5447d752eb8c29ac4f1ad4cafd1c

**Comment by GiuseppeChillemi** [comment]
It does not work
This is my json

```
{
    "red.buildDir": "'X:\\_Drives\\_DropBox%20Giuseppe%20Chillemi\\Dropbox\\Svi\\",
    "red.redPath": "'X:\\_Drives\\_DropBox%20Giuseppe%20Chillemi\\Dropbox\\Svi\\Red.exe",
    "red.rls-debug": true,
    "red.server.trace.server": "messages",
    "red.devOptions": [
    
    ]
}
```

Here it does not work, can't connect to the server.

I used all the permutations of this:
"'X:\\
"X:\\
"'X://
"X://

Version 0.3.6
June 14th 2020 build.

Do you see any problem in the file?

**Comment by GiuseppeChillemi** [comment]
Could you please include an example JSON with windows paths with spaces here?

I have tried again with no success putting read on main dir x:\ with no spaces but no luck here !



[Trace - 00:42:33] Sending request 'initialize - (0)'.
[Info  - 00:42:34] Connection to server got closed. Server will restart.

**Comment by GiuseppeChillemi** [comment]
Reverting to 0.3.5 solved all problems.
It also handles spaces in paths with new version.
0.3.6 is buggy!
