### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by ALANVF** [red/VScode-extension#38]
(Windows 10)
Whenever I open/create a Red project, I get this output in the console:
```
[Info  - 9:02:15 PM] Connection to server got closed. Server will restart.
[Info  - 9:02:16 PM] Connection to server got closed. Server will restart.
[Info  - 9:02:17 PM] Connection to server got closed. Server will restart.
[Info  - 9:02:18 PM] Connection to server got closed. Server will restart.
[Error - 9:02:19 PM] Connection to server got closed. Server will not be restarted.
```
I've tried restarting several times, and I have all of the settings configured correctly so I'm not sure what's wrong.

**Comment by avitkauskas** [comment]
Same for me on Mac OS VSCode Version: 1.37.1

**Comment by avitkauskas** [comment]
It works with the latest daily Red version (red-03sep19-8b5417f7 at this time).

**Comment by aseidlitz** [comment]
doesn't work for me:
macOS 10.14.6
red 0.6.4 (build Sep 16)
VSCode  1.38.1
red-auto 0.3.5

same Connection to server got closed.

**Comment by danieloff** [comment]
Also Windows 10
red 0.6.4 either the official release or the automated build of Nov 2
The official release crashes as mentioned in the first bug log
The automated build does not give me any messages of any kind but as far as I can tell the language server still doesn't start. I don't get any code completion/insight features

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Feel free to let me know if you have questions about my setup :)

**Comment by dirtbagger** [comment]
Yesterday I installed VSC and the red extension on my Windows 10 working machine.  Once I had things set up I tried a simple:

_print "hello world"_

What I get for "OUTPUT" every time is this:

_[Error - 7:11:44 a.m.] Starting client failed
Launching server using command C:\ProgramData\Red failed._

The folder "C:\ProgramData\Red" is where Red created the GUI console when I first ran the Red executable.  That must be Red's default location for the GUI console; I didn't choose to create that folder.  The Red executable does not reside there.

I've tried to find settings in VSC pointing at "C:\ProgramData\Red" but I can't find any.  Does anyone have any ideas as to what and where I need to make changes?

**Comment by kaltsoplyn** [comment]
Hi, Win 10 | red-0.6.4 | extension version 0.3.6 here, same error message and no language server.

_VS-Code:_
Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by bitbegin** [comment]
@dirtbagger @kaltsoplyn @danieloff  have you used `red-xxx.red --cli` to create the cli console? this extension need these files:
![image](https://user-images.githubusercontent.com/4469745/75679296-4b9dbf80-5cca-11ea-98a4-84e62a1fac57.png)

**Comment by bitbegin** [comment]
@aseidlitz can you check if there is console-xxx file in `~/.red folder` ?

**Comment by bitbegin** [comment]
there are two key points need to pay attension
![image](https://user-images.githubusercontent.com/4469745/75679881-6a508600-5ccb-11ea-9781-f3518077b987.png)

**Comment by dirtbagger** [comment]
Thanks @bitbegin.  I followed your advice.  I opened a cmd console and entered the following:
red-064.exe --cli
That seems to have worked as you describe.  However, since I posted about my problem, I have un-installed VSC, since it wasn't working for me.  I'll re-install VSC and the plug-in and see what happens.

**Comment by kaltsoplyn** [comment]
@bitbegin thanks! The problem was that I was using the main red-064 Windows exe download, which was producing a "console-2018-....exe", which is rather outdated. The "automated build" (currently "red-29feb20...exe") produces the right toolchain.   
Would it be a bad idea if the prompt for "latest daily version" was changed to "latest automated build" and a note that the extension won't work with the official red download or something, so that it's more clear?

**Comment by dirtbagger** [comment]
It turns out that after getting the cli set up, VSC with the Red plugin still won't work for me.  I think the original problem is solved, but that's just led to another problem.  The issue now might be that there are spaces in the Windows Path to where Red is installed.  Someday I might try changing that, but doing so would involve re-configuring a bunch of software, not just Red.  I don't have the time to spend on that right now.

**Comment by dirtbagger** [comment]
Well, I took the spaces out of my Windows Path.  Great, now I've progressed to the point that I can reproduce the error log described by ALANVF last August:

[Trace - 8:50:00 p.m.] Sending request 'initialize - (0)'.
[Info  - 8:50:01 p.m.] Connection to server got closed. Server will restart.
[Trace - 8:50:01 p.m.] Sending request 'initialize - (0)'.
[Info  - 8:50:02 p.m.] Connection to server got closed. Server will restart.
[Trace - 8:50:03 p.m.] Sending request 'initialize - (0)'.
[Info  - 8:50:04 p.m.] Connection to server got closed. Server will restart.
[Trace - 8:50:04 p.m.] Sending request 'initialize - (0)'.
[Info  - 8:50:05 p.m.] Connection to server got closed. Server will restart.
[Trace - 8:50:05 p.m.] Sending request 'initialize - (0)'.
[Error - 8:50:06 p.m.] Connection to server got closed. Server will not be restarted.

So, after quite a bit of effort, I'm still not able to use the Red plugin for VSC.

**Comment by termita81** [comment]
You can use symlinks even in Windows, if you don't want to change other software.
I also have problems on Windows 10.
I got latest exe (red-17apr20-ca0a2d5d5.exe), ran "red-17apr20-ca0a2d5d5.exe --cli", which resulted in 2 files under c:\ProgramData\Red\:
- console-2020-4-17-13897.exe
- crush-2020-4-17-13897.dll

I installed the Red extension in VSCode and am trying to work with the following script:
```
Red[
	Title:		"Calculator"
]
print 1
```
Compile Current Script (F7) results in
_C:\Users\User>cmd /c "c:/ProgramData/Red/console-2020-4-17-13897.exe" -c "c:/kit/red/scripts/easiest.red" -o "c:/kit/red/output/easiest.exe"
The filename, directory name, or volume label syntax is incorrect._

Run Current Script (F6) results in
_cmd /c "c:/ProgramData/Red/console-2020-4-17-13897.exe" --cli "c:/kit/red/scripts/easiest.red"
The filename, directory name, or volume label syntax is incorrect._

My settings.json file contains
    _"red.redPath": "c:\\ProgramData\\Red\\console-2020-4-17-13897.exe",
    "red.buildDir": "c:\\kit\\red\\output",_

**Comment by termita81** [comment]
Commenting out the following in commandsProvider.js seems to help
    _if (process.platform === 'win32') {
        //text = "cmd /c ";
    }_

**Comment by rsheehan** [comment]
I am running on MacOS 10.14.6 and haven't been able to get the server starting for quite sometime. I am using the latest distributions and extension 0.3.6. Thanks

**Comment by bitbegin** [comment]
@termita81 @dirtbagger @rsheehan  does 0.4.1 work for you?

**Comment by qtxie** [comment]
I cannot reproduce it now. Please try the latest version.
