### ISSUE TITLE
Letters "ch" are wrongly highlighted in the begining of the words

### ISSUE THREAD

**Issue by avitkauskas** [red/VScode-extension#39]
The letters "ch" are wrongly highlighted in the begining of the words:
<img width="265" alt="Screenshot 2019-09-04 at 09 42 02" src="https://user-images.githubusercontent.com/656586/64231430-49fc6600-cef8-11e9-9afd-812318147d8f.png">

**Comment by bitbegin** [comment]
https://github.com/red/VScode-extension/commit/8ae915185859bcd2ef80e79424b0ecc863de53db should fix this issue, just need release a new version

**Comment by vazub** [comment]
I don't experience this issue with 0.3.6 version of extension.
