### ISSUE TITLE
syntax error false positive for set-path! with paren

### ISSUE THREAD

**Issue by dander** [red/VScode-extension#40]
For the following code snippet:

```
Red []
x: [1 2 3]
x/(2): 4
probe x
```

The colon character has a red underline with the comment:
>invalid Syntax(get-word!)

**Comment by vazub** [comment]
There is similar issue for `:x/(2)`

Looking somewhat deeper into this, it seems like a language server issue.

**Comment by dander** [comment]
I can confirm this seems to be fixed in 0.4.0 now. Nice work overhauling this extension following the updated transcode engine, by the way 👍
