### ISSUE TITLE
There is missing char `R` in the name of month `February`

### ISSUE THREAD

**Issue by Oldes** [red/VScode-extension#46]
Check this line: https://github.com/red/VScode-extension/blob/ef58e239253f80325f271f17760a34b01f63b322/syntaxes/Red.tmLanguage.json#L395

There is `|Feb(u(a(ry?)?)?)?` but there should be: `|Feb(r(u(a(ry?)?)?)?)?`

**Comment by qtxie** [comment]
@Oldes Thanks for pointing it out.
