### ISSUE TITLE
Windows: Starting client failed

### ISSUE THREAD

**Issue by HunterZ** [red/VScode-extension#52]
Getting the following error on Windows 10:
```
[Error - 11:06:52 AM] Starting client failed
Launching server using command C:\ProgramData\Red failed.
```
It's completely ignoring my `red.redPath` setting. I've tried the following values:
```json
"red.redPath": "C:\\ProgramData\\chocolatey\\lib\\red\\tools\\red.exe"
"red.redPath": "C:\\ProgramData\\chocolatey\\lib\\red\\tools\\red.exe --cli"
"red.redPath": "C:\\ProgramData\\chocolatey\\lib\\red\\tools\\red.exe --CLI"
```

It's almost like it's looking in a hard-coded path and ignoring the `red.redPath` setting.

Also, red.exe is in my system PATH, so why do I even need to tell VSCode where to find it?

**Comment by qtxie** [comment]
> Also, red.exe is in my system PATH, so why do I even need to tell VSCode where to find it?

It cannot work properly in system PATH. https://github.com/red/red/issues/543

**Comment by qtxie** [comment]
I think this setting (red.redPath) is outdated in the latest plugin. Document needs to be updated. Please try the following command:
1. open the CMD on Windows.
2. run `> red.exe --cli` in the CMD to generate the CLI console.
3. restart the VSCode.

**Comment by HunterZ** [comment]
No, that just results in a different failure mode:
```
[Info  - 5:51:59 PM] Connection to server got closed. Server will restart.
[Info  - 5:52:00 PM] Connection to server got closed. Server will restart.
[Info  - 5:52:00 PM] Connection to server got closed. Server will restart.
[Info  - 5:52:01 PM] Connection to server got closed. Server will restart.
[Error - 5:52:02 PM] Connection to server got closed. Server will not be restarted.
```

Accompanying popup:
```
The Red Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

**Comment by qtxie** [comment]
@HunterZ Did you use the automated builds version of Red? 0.6.4 is way too outdated.

**Comment by HunterZ** [comment]
I used chocolatey to install, as mentioned on the official download page.

I didn't understand the comment on the extension about needing a newer build, so that's probably the problem. What a mess; I guess I'll check back later, as I'm not up for messing with manually installing cutting edge builds of things at the moment.

**Comment by qtxie** [comment]
You don't need to _**install**_ Red. Just download it and use it directly. ;-)
