### ISSUE TITLE
user-created word names containing a hyphen don't appear in the drop-down suggestion list

### ISSUE THREAD

**Issue by michaeldesu** [red/VScode-extension#8]
Create your own word name with a hyphen, then go somewhere else in the code, and the type the first few chars of that word, and it wont appear in the drop down.

**Comment by geekyi** [comment]
I don't think user created words appear at all in drop-down with or without `-` (at least not for me)

**Comment by michaeldesu** [comment]
@geekyi thanks - you're right, I hadn't noticed that. Also looks like function names are not displayed either. All in all, seems like just the Red keywords are displayed.

**Comment by qtxie** [comment]
Fixed in v0.3
